name: Nightly Release

on:
  push:
    branches: [master]

jobs:
  tests:
    uses: ./.github/workflows/test.yml

  package:
    name: "Package ${{ matrix.platform }}"
    needs: [tests]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux-x86_64, macos-arm64, macos-x86_64, windows-x86_64]

    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4

    - name: Create extension package
      run: python release/package.py --platform ${{ matrix.platform }}

    - name: Advance `latest` tag
      if: matrix.platform == 'linux-x86_64'
      uses: actions/github-script@v6
      with:
        script: |
          try {
            await github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "tags/latest"
            })
          } catch (e) {
            console.log("The latest tag doesn't exist yet: " + e)
          }
          await github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/latest",
            sha: context.sha
          })

    - name: Create GitHub nightly release
      uses: ncipollo/release-action@v1
      with:
        name: "Nightly Release"
        prerelease: true
        allowUpdates: true
        replacesArtifacts: true
        artifacts: "mitsuba-blender-${{ matrix.platform }}.zip"
        artifactErrorsFailBuild: true
        tag: "latest"
        bodyFile: "release/nightly_release_body.md"
